package components;

import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author windows
 */
public class MainLayout extends javax.swing.JPanel {

    public MainLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLayout = new javax.swing.JPanel();
        navPanel = new javax.swing.JPanel();
        mainPageBtn = new javax.swing.JButton();
        facultyManageBtn = new javax.swing.JButton();
        subjectManageBtn = new javax.swing.JButton();
        studentManageBtn = new javax.swing.JButton();
        professorManageBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        mainLayout.setBackground(new java.awt.Color(255, 137, 47));
        mainLayout.setFont(mainLayout.getFont());
        mainLayout.setPreferredSize(new java.awt.Dimension(1280, 720));

        navPanel.setBackground(new java.awt.Color(255, 137, 47));
        navPanel.setPreferredSize(new java.awt.Dimension(300, 324));

        mainPageBtn.setBackground(new java.awt.Color(228, 109, 18));
        mainPageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        mainPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainPageBtn.setText("หน้าหลัก");
        mainPageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainPageBtn.setIconTextGap(10);
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        facultyManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        facultyManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        facultyManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        facultyManageBtn.setText("จัดการคณะ/สาขา");
        facultyManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        facultyManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facultyManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        facultyManageBtn.setIconTextGap(10);

        subjectManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        subjectManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        subjectManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        subjectManageBtn.setText("จัดการวิชาเรียน");
        subjectManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        subjectManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subjectManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subjectManageBtn.setIconTextGap(10);

        studentManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        studentManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        studentManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        studentManageBtn.setText("จัดการนักศึกษา");
        studentManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        studentManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentManageBtn.setIconTextGap(10);
        studentManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManageBtnActionPerformed(evt);
            }
        });

        professorManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        professorManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        professorManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        professorManageBtn.setText("จัดการอาจารย์");
        professorManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        professorManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        professorManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        professorManageBtn.setIconTextGap(10);
        professorManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorManageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(facultyManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            .addComponent(subjectManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(professorManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addComponent(mainPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(facultyManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(subjectManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(studentManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(professorManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setPreferredSize(new java.awt.Dimension(991, 720));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayoutLayout = new javax.swing.GroupLayout(mainLayout);
        mainLayout.setLayout(mainLayoutLayout);
        mainLayoutLayout.setHorizontalGroup(
            mainLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayoutLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainLayoutLayout.setVerticalGroup(
            mainLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPageBtnActionPerformed

    private void studentManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentManageBtnActionPerformed

    private void professorManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorManageBtnActionPerformed

    public JPanel getMainlayout() {
        return mainLayout;
    }

    public JPanel getNavPanel() {
        return navPanel;
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    /* Buttons */
    public JButton getProfessorManageBtn() {
        return professorManageBtn;
    }

    public JButton getFacultyManageBtn() {
        return facultyManageBtn;
    }

    public JButton getMainPageBtn() {
        return mainPageBtn;
    }

    public JButton getStudentManageBtn() {
        return studentManageBtn;
    }

    public JButton getSubjectManageBtn() {
        return subjectManageBtn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton facultyManageBtn;
    private javax.swing.JPanel mainLayout;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton professorManageBtn;
    private javax.swing.JButton studentManageBtn;
    private javax.swing.JButton subjectManageBtn;
    // End of variables declaration//GEN-END:variables
}
