package components;

import javax.swing.*;

public class NavPanel extends javax.swing.JPanel {
    
    private JButton allBtns[] = new JButton[5];
    
    public NavPanel() {
        initComponents();
        allBtns[0] = facultyManageBtn;
        allBtns[1] = mainPageBtn;
        allBtns[2] = professorManageBtn;
        allBtns[3] = studentManageBtn;
        allBtns[4] = subjectManageBtn;
    }
    
    public JButton getFacultyManageBtn() {
        return facultyManageBtn;
    }
    
    public JButton getMainPageBtn() {
        return mainPageBtn;
    }
    
    public JButton getProfessorManageBtn() {
        return professorManageBtn;
    }
    
    public JButton getStudentManageBtn() {
        return studentManageBtn;
    }
    
    public JButton getSubjectManageBtn() {
        return subjectManageBtn;
    }

    public JButton getLogOutBtn() {
        return logOutBtn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void clearBtnColorized() {
        for (JButton eachBtn : allBtns) {
            eachBtn.setBackground(new java.awt.Color(253, 249, 245));
            eachBtn.setForeground(new java.awt.Color(255, 137, 47));
        }
        mainPageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/home.png")));
        studentManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/student.png")));
        professorManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/professor.png")));
        subjectManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/book.png")));
        facultyManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/faculty.png")));
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appName = new javax.swing.JLabel();
        appDescription = new javax.swing.JLabel();
        buttonsWrapper = new javax.swing.JPanel();
        mainPageBtn = new javax.swing.JButton();
        facultyManageBtn = new javax.swing.JButton();
        subjectManageBtn = new javax.swing.JButton();
        studentManageBtn = new javax.swing.JButton();
        professorManageBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        appName1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 137, 47));
        setPreferredSize(new java.awt.Dimension(286, 720));

        appName.setFont(new java.awt.Font("Prompt Semibold", 0, 24)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("Hi , Admin");

        appDescription.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        appDescription.setForeground(new java.awt.Color(253, 199, 158));
        appDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appDescription.setText("ระบบจัดการบุคลากรและ นักศึกษา");

        buttonsWrapper.setBackground(new java.awt.Color(255, 137, 47));
        buttonsWrapper.setLayout(new java.awt.GridLayout(5, 1, 0, 4));

        mainPageBtn.setBackground(new java.awt.Color(228, 109, 18));
        mainPageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        mainPageBtn.setForeground(new java.awt.Color(253, 249, 245));
        mainPageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-selected.png"))); // NOI18N
        mainPageBtn.setText("หน้าหลัก");
        mainPageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainPageBtn.setFocusable(false);
        mainPageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainPageBtn.setIconTextGap(10);
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });
        buttonsWrapper.add(mainPageBtn);

        facultyManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        facultyManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        facultyManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        facultyManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/faculty.png"))); // NOI18N
        facultyManageBtn.setText("จัดการคณะ/สาขา");
        facultyManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        facultyManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facultyManageBtn.setFocusPainted(false);
        facultyManageBtn.setFocusable(false);
        facultyManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        facultyManageBtn.setIconTextGap(10);
        facultyManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyManageBtnActionPerformed(evt);
            }
        });
        buttonsWrapper.add(facultyManageBtn);

        subjectManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        subjectManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        subjectManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        subjectManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        subjectManageBtn.setText("จัดการวิชาเรียน");
        subjectManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        subjectManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectManageBtn.setFocusPainted(false);
        subjectManageBtn.setFocusable(false);
        subjectManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subjectManageBtn.setIconTextGap(10);
        subjectManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectManageBtnActionPerformed(evt);
            }
        });
        buttonsWrapper.add(subjectManageBtn);

        studentManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        studentManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        studentManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        studentManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        studentManageBtn.setText("จัดการนักศึกษา");
        studentManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        studentManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentManageBtn.setFocusPainted(false);
        studentManageBtn.setFocusable(false);
        studentManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentManageBtn.setIconTextGap(10);
        studentManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManageBtnActionPerformed(evt);
            }
        });
        buttonsWrapper.add(studentManageBtn);

        professorManageBtn.setBackground(new java.awt.Color(253, 249, 245));
        professorManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        professorManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        professorManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/professor.png"))); // NOI18N
        professorManageBtn.setText("จัดการอาจารย์");
        professorManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        professorManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        professorManageBtn.setFocusPainted(false);
        professorManageBtn.setFocusable(false);
        professorManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        professorManageBtn.setIconTextGap(10);
        professorManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorManageBtnActionPerformed(evt);
            }
        });
        buttonsWrapper.add(professorManageBtn);

        logOutBtn.setBackground(new java.awt.Color(243, 81, 45));
        logOutBtn.setFont(new java.awt.Font("Prompt", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(253, 249, 245));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        logOutBtn.setText(" Logout");
        logOutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logOutBtn.setFocusPainted(false);
        logOutBtn.setRequestFocusEnabled(false);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        appName1.setFont(new java.awt.Font("Prompt Semibold", 0, 24)); // NOI18N
        appName1.setForeground(new java.awt.Color(255, 255, 255));
        appName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName1.setText("WAIDO-KMITL");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(buttonsWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(appName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(appDescription)
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonsWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(appName1)
                    .addContainerGap(650, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        /* Change color of btn after it was clicked 🎨 */
        clearBtnColorized();
        mainPageBtn.setBackground(new java.awt.Color(228, 109, 18));
        mainPageBtn.setForeground(new java.awt.Color(253, 249, 245));
        mainPageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/home-selected.png")));
    }//GEN-LAST:event_mainPageBtnActionPerformed

    private void studentManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManageBtnActionPerformed
        /* Change color of btn after it was clicked 🎨 */
        clearBtnColorized();
        studentManageBtn.setBackground(new java.awt.Color(228, 109, 18));
        studentManageBtn.setForeground(new java.awt.Color(253, 249, 245));
        studentManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/student-selected.png")));
    }//GEN-LAST:event_studentManageBtnActionPerformed

    private void professorManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorManageBtnActionPerformed
        /* Change color of btn after it was clicked 🎨 */
        clearBtnColorized();
        professorManageBtn.setBackground(new java.awt.Color(228, 109, 18));
        professorManageBtn.setForeground(new java.awt.Color(253, 249, 245));
        professorManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/professor-selected.png")));
    }//GEN-LAST:event_professorManageBtnActionPerformed

    private void subjectManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectManageBtnActionPerformed
        /* Change color of btn after it was clicked 🎨 */
        clearBtnColorized();
        subjectManageBtn.setBackground(new java.awt.Color(228, 109, 18));
        subjectManageBtn.setForeground(new java.awt.Color(253, 249, 245));
        subjectManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/book-selected.png")));
    }//GEN-LAST:event_subjectManageBtnActionPerformed

    private void facultyManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyManageBtnActionPerformed
        /* Change color of btn after it was clicked 🎨 */
        clearBtnColorized();
        facultyManageBtn.setBackground(new java.awt.Color(228, 109, 18));
        facultyManageBtn.setForeground(new java.awt.Color(253, 249, 245));
        facultyManageBtn.setIcon(new ImageIcon(getClass().getResource("/icons/faculty-selected.png")));
    }//GEN-LAST:event_facultyManageBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appDescription;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel appName1;
    private javax.swing.JPanel buttonsWrapper;
    private javax.swing.JButton facultyManageBtn;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JButton professorManageBtn;
    private javax.swing.JButton studentManageBtn;
    private javax.swing.JButton subjectManageBtn;
    // End of variables declaration//GEN-END:variables

}
