package page;

import components.*;
import frame.AddNewBranchStudentFrame;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import model.Student;
import model.StudentModel;

public class BranchStudentManagePanel extends JPanel implements ActionListener {

    private AddNewBranchStudentFrame addNewBranchStudentFrame; // Internal frame
    private StudentModel studentModel = new StudentModel();
    private String nameBranch = "";

    public BranchStudentManagePanel(String nameBranch, String nameFaculty) {
        this.nameBranch = nameBranch;
        initComponents();
        initTable();
        facultyNameHeader.setText(nameFaculty);
        branchNameHeader.setText(nameBranch);
//        this.headerSeparator.setText(facultyName);
    }

    public void initTable() {
        ArrayList<Student> students = studentModel.getStudyInBranch(nameBranch);
        getStudentTable().setViewDataBtnColumn(5);

        this.getStudentTable().clearTable();
        for (int i = 0; i < students.size(); i++) {
            Student student = students.get(i);
            Object[] object = {null, student.getFullname(), student.getStudentId(), student.getFaculty() + "/" + student.getBranch(), student.getGender()};
            this.getStudentTable().addRow(object);
        }
    }

    public StudentModel getStudentModel() {
        return studentModel;
    }
    
    public void setNameBranch(String nameBranch) {
        this.nameBranch = nameBranch;
    }
    
    public Table getStudentTable() {
        return this.studentTable;
    }

    public JButton getAddStudentBtn() {
        return this.addStudent;
    }

    public JButton getDeleteStudentBtn() {
        return this.deleteStudent;
    }

    public JLabel getGoBackLabel() {
        return this.goBackLabel;
    }
    
    public void createAddNewBranchStudentFrame() {
        this.addNewBranchStudentFrame = new AddNewBranchStudentFrame();
        addNewBranchStudentFrame.getAddStudentBtn().addActionListener(this);
    }
    public void configAddNewBranchStudentFrame() {
        this.addNewBranchStudentFrame.config();
    }
    
    public void deleteStudent() {
        for (int i = 0; i < this.getStudentTable().getRowCount(); i++) {
            Boolean selected = (Boolean) this.getStudentTable().getModel().getValueAt(i, 0);
            if (selected == null) {
                selected = false;
            }
            String studentID = this.getStudentTable().getModel().getValueAt(i, 2).toString();
            if (selected) {
                this.getStudentModel().deleteBranch(studentID);
            }
        }
        this.initTable();
    }

    @Override
    public void actionPerformed(ActionEvent event) {
        if (event.getSource().equals(addNewBranchStudentFrame.getAddStudentBtn())) {
            // Clicked on add new subject btn
            // check in DB
            String studentName = addNewBranchStudentFrame.getStudentNameComboBox().getSelectedItem().toString();
            if (!studentName.isBlank()) {
                if (!studentModel.updateStudent(studentName, facultyNameHeader.getText(), branchNameHeader.getText())) {
                    JOptionPane.showMessageDialog(addNewBranchStudentFrame, "Error, make sure your data is correctly", "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            this.initTable();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        northPanelWrapper = new javax.swing.JPanel();
        goBackLabel = new javax.swing.JLabel();
        nameHeader = new javax.swing.JPanel();
        facultyNameHeader = new javax.swing.JLabel();
        hederSeparator = new javax.swing.JLabel();
        branchNameHeader = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        actionWrapper = new javax.swing.JPanel();
        buttonsWrapper = new javax.swing.JPanel();
        deleteStudent = new javax.swing.JButton();
        addStudent = new javax.swing.JButton();
        findStudent = new javax.swing.JTextField();
        tableScrollPane = new javax.swing.JScrollPane();
        studentTable = new components.Table();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new java.awt.BorderLayout(0, 5));

        northPanel.setBackground(new java.awt.Color(255, 255, 255));
        northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.PAGE_AXIS));

        northPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));
        northPanelWrapper.setLayout(new java.awt.BorderLayout());

        goBackLabel.setBackground(new java.awt.Color(255, 137, 47));
        goBackLabel.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        goBackLabel.setForeground(new java.awt.Color(255, 137, 47));
        goBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        goBackLabel.setText("กลับ");
        goBackLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        goBackLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        goBackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackLabel.setMaximumSize(new java.awt.Dimension(73, 31));
        goBackLabel.setPreferredSize(new java.awt.Dimension(63, 50));
        northPanelWrapper.add(goBackLabel, java.awt.BorderLayout.LINE_START);

        nameHeader.setBackground(new java.awt.Color(255, 255, 255));

        facultyNameHeader.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        facultyNameHeader.setForeground(new java.awt.Color(93, 93, 93));
        facultyNameHeader.setText("คณะเทคโนโลยีสารสนเทศ");
        facultyNameHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        facultyNameHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        hederSeparator.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        hederSeparator.setForeground(new java.awt.Color(210, 210, 210));
        hederSeparator.setText("/");
        hederSeparator.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hederSeparator.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        branchNameHeader.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        branchNameHeader.setForeground(new java.awt.Color(93, 93, 93));
        branchNameHeader.setText("สาขา IT");
        branchNameHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        branchNameHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout nameHeaderLayout = new javax.swing.GroupLayout(nameHeader);
        nameHeader.setLayout(nameHeaderLayout);
        nameHeaderLayout.setHorizontalGroup(
            nameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameHeaderLayout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(facultyNameHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hederSeparator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchNameHeader))
        );
        nameHeaderLayout.setVerticalGroup(
            nameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(nameHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hederSeparator)
                    .addComponent(branchNameHeader)
                    .addComponent(facultyNameHeader)))
        );

        northPanelWrapper.add(nameHeader, java.awt.BorderLayout.CENTER);

        northPanel.add(northPanelWrapper);

        headerSeparator.setForeground(new java.awt.Color(193, 193, 193));
        headerSeparator.setPreferredSize(new java.awt.Dimension(950, 2));
        northPanel.add(headerSeparator);

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(249, 249, 249));

        actionWrapper.setBackground(new java.awt.Color(249, 249, 249));
        actionWrapper.setLayout(new java.awt.BorderLayout());

        buttonsWrapper.setLayout(new java.awt.BorderLayout(5, 0));

        deleteStudent.setBackground(new java.awt.Color(249, 249, 249));
        deleteStudent.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        deleteStudent.setForeground(new java.awt.Color(230, 63, 63));
        deleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        deleteStudent.setText("ลบนักศึกษาออก");
        deleteStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 63, 63), 2, true));
        deleteStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteStudent.setMargin(new java.awt.Insets(2, 5, 3, 5));
        deleteStudent.setPreferredSize(new java.awt.Dimension(140, 40));
        deleteStudent.setRequestFocusEnabled(false);
        deleteStudent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        buttonsWrapper.add(deleteStudent, java.awt.BorderLayout.LINE_START);

        addStudent.setBackground(new java.awt.Color(255, 137, 47));
        addStudent.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        addStudent.setForeground(new java.awt.Color(255, 255, 255));
        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addStudent.setText("เพิ่มนักศึกษา");
        addStudent.setBorder(null);
        addStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStudent.setMargin(new java.awt.Insets(2, 5, 3, 5));
        addStudent.setPreferredSize(new java.awt.Dimension(120, 40));
        addStudent.setRequestFocusEnabled(false);
        addStudent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        buttonsWrapper.add(addStudent, java.awt.BorderLayout.EAST);

        actionWrapper.add(buttonsWrapper, java.awt.BorderLayout.EAST);

        findStudent.setColumns(20);
        findStudent.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        findStudent.setForeground(new java.awt.Color(93, 93, 93));
        findStudent.setToolTipText("");
        findStudent.setActionCommand("<Not Set>");
        findStudent.setAutoscrolls(false);
        findStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ค้นหาผู้เรียน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Prompt", 0, 12), new java.awt.Color(149, 149, 149))); // NOI18N
        findStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        findStudent.setMargin(new java.awt.Insets(2, 24, 2, 24));
        findStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findStudentActionPerformed(evt);
            }
        });
        actionWrapper.add(findStudent, java.awt.BorderLayout.LINE_START);

        tableScrollPane.setBorder(null);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "การเลือก", "ชื่อ-นามสกุล", "รหัสนึกศึกษา", "คณะ/สาขา", "เพศ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableScrollPane.setViewportView(studentTable);
        if (studentTable.getColumnModel().getColumnCount() > 0) {
            studentTable.getColumnModel().getColumn(0).setMinWidth(80);
            studentTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            studentTable.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE))
                .addContainerGap())
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void findStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findStudentActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionWrapper;
    private javax.swing.JButton addStudent;
    private javax.swing.JLabel branchNameHeader;
    private javax.swing.JPanel buttonsWrapper;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JLabel facultyNameHeader;
    private javax.swing.JTextField findStudent;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JLabel hederSeparator;
    private javax.swing.JPanel nameHeader;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel northPanelWrapper;
    private components.Table studentTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
