package page;

import frame.AddNewBranchFrame;
import components.*;
import java.awt.event.*;
import javax.swing.*;
import model.FacultyModel;

public class BranchManagePanel extends JPanel implements ActionListener {

    private AddNewBranchFrame addNewBranchFrame;
//    private FacultyModel facultyModel = new FacultyModel();

    public BranchManagePanel() {
        initComponents();
    }

    public Table getTable() {
        return this.branchTable;
    }

    public JButton getAddBranchBtn() {
        return this.addBranch;
    }

    public JButton getDeleteBranchBtn() {
        return this.deleteBranch;
    }

    public JLabel getGoBackLabel() {
        return this.goBackLabel;
    }

    public AddNewBranchFrame getAddNewBranchFrame() {
        return this.addNewBranchFrame;
    }

    public void createAddNewBranchFrame() {
        this.addNewBranchFrame = new AddNewBranchFrame();
        addNewBranchFrame.getAddBranchBtn().addActionListener(this);
    }

    public void configAddNewBranchFrame() {
        this.addNewBranchFrame.config();
    }

    @Override
    public void actionPerformed(ActionEvent event) {
        if (event.getSource().equals(addNewBranchFrame.getAddBranchBtn())) {

//            facultyModel.insert(addNewBranchFrame.getFacultyNameTextField().getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        northPanelWrapper = new javax.swing.JPanel();
        goBackLabel = new javax.swing.JLabel();
        branchNameHeader = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        actionWrapper = new javax.swing.JPanel();
        buttonsWrapper = new javax.swing.JPanel();
        deleteBranch = new javax.swing.JButton();
        addBranch = new javax.swing.JButton();
        findBranch = new javax.swing.JTextField();
        tableScrollPane = new javax.swing.JScrollPane();
        branchTable = new components.Table();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new java.awt.BorderLayout(0, 5));

        northPanel.setBackground(new java.awt.Color(255, 255, 255));
        northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.PAGE_AXIS));

        northPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));
        northPanelWrapper.setLayout(new java.awt.BorderLayout());

        goBackLabel.setBackground(new java.awt.Color(255, 137, 47));
        goBackLabel.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        goBackLabel.setForeground(new java.awt.Color(255, 137, 47));
        goBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        goBackLabel.setText("กลับ");
        goBackLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        goBackLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        goBackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackLabel.setMaximumSize(new java.awt.Dimension(73, 31));
        goBackLabel.setPreferredSize(new java.awt.Dimension(63, 50));
        northPanelWrapper.add(goBackLabel, java.awt.BorderLayout.LINE_START);

        branchNameHeader.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        branchNameHeader.setForeground(new java.awt.Color(93, 93, 93));
        branchNameHeader.setText("คณะเทคโนโลยีสารสนเทศ");
        branchNameHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        branchNameHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        northPanelWrapper.add(branchNameHeader, java.awt.BorderLayout.EAST);

        northPanel.add(northPanelWrapper);

        headerSeparator.setForeground(new java.awt.Color(193, 193, 193));
        headerSeparator.setPreferredSize(new java.awt.Dimension(950, 2));
        northPanel.add(headerSeparator);

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(249, 249, 249));

        actionWrapper.setBackground(new java.awt.Color(249, 249, 249));
        actionWrapper.setLayout(new java.awt.BorderLayout());

        buttonsWrapper.setLayout(new java.awt.BorderLayout(5, 0));

        deleteBranch.setBackground(new java.awt.Color(249, 249, 249));
        deleteBranch.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        deleteBranch.setForeground(new java.awt.Color(230, 63, 63));
        deleteBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        deleteBranch.setText("ลบสาขาที่เลือก");
        deleteBranch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 63, 63), 2, true));
        deleteBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBranch.setMargin(new java.awt.Insets(2, 5, 3, 5));
        deleteBranch.setPreferredSize(new java.awt.Dimension(140, 40));
        deleteBranch.setRequestFocusEnabled(false);
        deleteBranch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        deleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBranchActionPerformed(evt);
            }
        });
        buttonsWrapper.add(deleteBranch, java.awt.BorderLayout.LINE_START);

        addBranch.setBackground(new java.awt.Color(255, 137, 47));
        addBranch.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        addBranch.setForeground(new java.awt.Color(255, 255, 255));
        addBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addBranch.setText("เพิ่มสาขา");
        addBranch.setBorder(null);
        addBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBranch.setMargin(new java.awt.Insets(2, 5, 3, 5));
        addBranch.setPreferredSize(new java.awt.Dimension(100, 40));
        addBranch.setRequestFocusEnabled(false);
        addBranch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bin.png"))); // NOI18N
        addBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchActionPerformed(evt);
            }
        });
        buttonsWrapper.add(addBranch, java.awt.BorderLayout.EAST);

        actionWrapper.add(buttonsWrapper, java.awt.BorderLayout.EAST);

        findBranch.setColumns(20);
        findBranch.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        findBranch.setForeground(new java.awt.Color(93, 93, 93));
        findBranch.setToolTipText("");
        findBranch.setActionCommand("<Not Set>");
        findBranch.setAutoscrolls(false);
        findBranch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ค้นหาสาขา", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Prompt", 0, 12), new java.awt.Color(149, 149, 149))); // NOI18N
        findBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        findBranch.setMargin(new java.awt.Insets(2, 24, 2, 24));
        findBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBranchActionPerformed(evt);
            }
        });
        actionWrapper.add(findBranch, java.awt.BorderLayout.LINE_START);

        tableScrollPane.setBorder(null);

        branchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "การเลือก", "ชื่อสาขา", "จำนวนผู้เรียน", "ดูข้อมูล"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableScrollPane.setViewportView(branchTable);
        if (branchTable.getColumnModel().getColumnCount() > 0) {
            branchTable.getColumnModel().getColumn(0).setMinWidth(80);
            branchTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            branchTable.getColumnModel().getColumn(0).setMaxWidth(80);
            branchTable.getColumnModel().getColumn(3).setMinWidth(100);
            branchTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            branchTable.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE))
                .addContainerGap())
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void findBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBranchActionPerformed

    private void deleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBranchActionPerformed

    private void addBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBranchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionWrapper;
    private javax.swing.JButton addBranch;
    private javax.swing.JLabel branchNameHeader;
    private components.Table branchTable;
    private javax.swing.JPanel buttonsWrapper;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteBranch;
    private javax.swing.JTextField findBranch;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel northPanelWrapper;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
