package page;

import javax.swing.*;
import model.ProfessorModel;
import model.Professor;
import java.util.ArrayList;

public class EachProfessorManagePanel extends JPanel {

    private ProfessorModel professorModel = new ProfessorModel();
    private Professor professor;

    public EachProfessorManagePanel(String professorFullname) {
        initComponents();
        this.setProfessor(professorModel.getProfessor(professorFullname));
        this.professorDetailInit();
    }

    public void professorDetailInit() {
        this.getProfessorHeaderLabel().setText("จัดการอาจารย์ (" + professor.getFullname() + ")");
        this.getFullnameLabel().setText(professor.getFullname());
        this.getGenderLabel().setText(professor.getGender());
        this.getAgeLabel().setText(professor.getAge());
        this.getPhoneLabel().setText(professor.getPhone());
        this.getDegree().setText(professor.getDegree());
        this.getSubjectList().setModel(new AbstractListModel<String>() {
            ArrayList<String> subjectList = professorModel.getSubjetList(professor.getFullname());

            @Override
            public int getSize() {
                return subjectList.size();
            }

            @Override
            public String getElementAt(int i) {
                return subjectList.get(i);
            }
        });
    }

    public JLabel getDegree() {
        return degree;
    }

    public JLabel getAgeLabel() {
        return age;
    }

    public JLabel getFacultyLabel() {
        return degree;
    }

    public JLabel getFullnameLabel() {
        return fullname;
    }

    public JLabel getGenderLabel() {
        return gender;
    }

    public JLabel getProfessorHeaderLabel() {
        return professorHeader;
    }

    public JLabel getPhoneLabel() {
        return phone;
    }

    public ProfessorModel getProfessorModel() {
        return professorModel;
    }

    public JLabel getGoBackLabel() {
        return this.goBackLabel;
    }

    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    public JList<String> getSubjectList() {
        return subjectList;
    }

    public Professor getStudent() {
        return this.professor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        northPanelWrapper = new javax.swing.JPanel();
        goBackLabel = new javax.swing.JLabel();
        professorHeader = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        studentDetailWrapper = new javax.swing.JPanel();
        fullnameLabel = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        degreeLabel = new javax.swing.JLabel();
        degree = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        studentSubjectsWrapper = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        subjectsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subjectList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new java.awt.BorderLayout(0, 5));

        northPanel.setBackground(new java.awt.Color(255, 255, 255));
        northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.PAGE_AXIS));

        northPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));
        northPanelWrapper.setLayout(new java.awt.BorderLayout());

        goBackLabel.setBackground(new java.awt.Color(255, 137, 47));
        goBackLabel.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        goBackLabel.setForeground(new java.awt.Color(255, 137, 47));
        goBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        goBackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        goBackLabel.setText("กลับ");
        goBackLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        goBackLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        goBackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackLabel.setMaximumSize(new java.awt.Dimension(73, 31));
        goBackLabel.setPreferredSize(new java.awt.Dimension(63, 50));
        goBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackLabelMouseClicked(evt);
            }
        });
        northPanelWrapper.add(goBackLabel, java.awt.BorderLayout.LINE_START);

        professorHeader.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        professorHeader.setForeground(new java.awt.Color(93, 93, 93));
        professorHeader.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        professorHeader.setText("จัดการอาจารย์ (ดร.อาทิเชษ ศรีปัญญา)");
        professorHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        professorHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        professorHeader.setPreferredSize(new java.awt.Dimension(600, 53));
        northPanelWrapper.add(professorHeader, java.awt.BorderLayout.CENTER);

        northPanel.add(northPanelWrapper);

        headerSeparator.setForeground(new java.awt.Color(193, 193, 193));
        headerSeparator.setPreferredSize(new java.awt.Dimension(950, 2));
        northPanel.add(headerSeparator);

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setForeground(new java.awt.Color(93, 93, 93));

        studentDetailWrapper.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailWrapper.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

        fullnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        fullnameLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        fullnameLabel.setText("ชื่อจริง-นามสกุล");
        studentDetailWrapper.add(fullnameLabel);

        fullname.setBackground(new java.awt.Color(255, 255, 255));
        fullname.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        fullname.setForeground(new java.awt.Color(134, 134, 134));
        fullname.setText("นายศุภกร เนตรสุวรรณ");
        studentDetailWrapper.add(fullname);

        degreeLabel.setBackground(new java.awt.Color(255, 255, 255));
        degreeLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        degreeLabel.setText("ระดับการศึกษา");
        studentDetailWrapper.add(degreeLabel);

        degree.setBackground(new java.awt.Color(255, 255, 255));
        degree.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        degree.setForeground(new java.awt.Color(134, 134, 134));
        degree.setText("ปริญญาเอก");
        studentDetailWrapper.add(degree);

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        genderLabel.setText("เพศ");
        studentDetailWrapper.add(genderLabel);

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(134, 134, 134));
        gender.setText("ชาย");
        studentDetailWrapper.add(gender);

        ageLabel.setBackground(new java.awt.Color(255, 255, 255));
        ageLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        ageLabel.setText("อายุ");
        studentDetailWrapper.add(ageLabel);

        age.setBackground(new java.awt.Color(255, 255, 255));
        age.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(134, 134, 134));
        age.setText("20");
        studentDetailWrapper.add(age);

        phoneLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        phoneLabel.setText("เบอร์โทรศัพท์");
        studentDetailWrapper.add(phoneLabel);

        phone.setBackground(new java.awt.Color(255, 255, 255));
        phone.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(134, 134, 134));
        phone.setText("0959259515");
        studentDetailWrapper.add(phone);

        studentSubjectsWrapper.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout studentSubjectsWrapperLayout = new javax.swing.GroupLayout(studentSubjectsWrapper);
        studentSubjectsWrapper.setLayout(studentSubjectsWrapperLayout);
        studentSubjectsWrapperLayout.setHorizontalGroup(
            studentSubjectsWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        studentSubjectsWrapperLayout.setVerticalGroup(
            studentSubjectsWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        subjectsLabel.setBackground(new java.awt.Color(255, 255, 255));
        subjectsLabel.setFont(new java.awt.Font("Prompt Medium", 0, 14)); // NOI18N
        subjectsLabel.setText("วิชาที่สอน");

        subjectList.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        subjectList.setForeground(new java.awt.Color(134, 134, 134));
        subjectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "วิชา xxx-1", "วิชา xxx-2", "วิชา  yyyy-1", "วิชา  yyzz-2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        subjectList.setSelectionBackground(new java.awt.Color(255, 137, 47));
        subjectList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(subjectList);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentDetailWrapper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(subjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentSubjectsWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(studentDetailWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(studentSubjectsWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackLabelMouseClicked

    }//GEN-LAST:event_goBackLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel degree;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel goBackLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel northPanelWrapper;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel professorHeader;
    private javax.swing.JPanel studentDetailWrapper;
    private javax.swing.JPanel studentSubjectsWrapper;
    private javax.swing.JList<String> subjectList;
    private javax.swing.JLabel subjectsLabel;
    // End of variables declaration//GEN-END:variables
}
