package page;

import components.Barchart;
import components.Piechart;
import javax.swing.*;
import java.awt.*;
import model.ProfessorModel;
import model.FacultyModel;

public class HomePanel extends javax.swing.JPanel {

    private Piechart piechart = new Piechart();
    private Barchart barchart = new Barchart();
    private ProfessorModel professorModel = new ProfessorModel();
    private FacultyModel facultyModel = new FacultyModel();

    public HomePanel() {
        initComponents();
        init();
        paintChart();
    }

    public void init() {

    }

    public void paintChart() {
        this.getPanel1().add(
            piechart.createPiePanel("อัตราส่วนวิชาที่อาจารย์สอนต่อท่าน",
            professorModel.getProfessorDataForPiechart())
        );
        this.getPanel2().add(
            barchart.createBarPanel("อัตราส่วนนักศึกษาต่อคณะและสาขา",
            facultyModel.getFacultyDataForBarchart())
        );

    }

    public JPanel getPanel1() {
        return panel1;
    }

    public JPanel getPanel2() {
        return panel2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        northPanel = new javax.swing.JPanel();
        pageHeader = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        centerPanel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setLayout(new java.awt.BorderLayout());

        northPanel.setBackground(new java.awt.Color(255, 255, 255));
        northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.PAGE_AXIS));

        pageHeader.setFont(new java.awt.Font("Prompt", 1, 28)); // NOI18N
        pageHeader.setForeground(new java.awt.Color(93, 93, 93));
        pageHeader.setText("หนัาหลัก");
        pageHeader.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pageHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        northPanel.add(pageHeader);

        headerSeparator.setForeground(new java.awt.Color(193, 193, 193));
        headerSeparator.setPreferredSize(new java.awt.Dimension(950, 2));
        northPanel.add(headerSeparator);

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(249, 249, 249));
        centerPanel.setLayout(new java.awt.GridLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 153));
        panel1.setLayout(new java.awt.BorderLayout());
        centerPanel.add(panel1);

        panel2.setBackground(new java.awt.Color(51, 255, 51));
        panel2.setLayout(new java.awt.BorderLayout());
        centerPanel.add(panel2);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JPanel northPanel;
    private javax.swing.JLabel pageHeader;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
