package page;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author windows
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    public JPanel getWrapper() {
        return Wrapper;
    }

    public void setWrapper(JPanel Wrapper) {
        this.Wrapper = Wrapper;
    }

    public JLabel getAppDescription() {
        return appDescription;
    }

    public void setAppDescription(JLabel appDescription) {
        this.appDescription = appDescription;
    }

    public JLabel getAppName() {
        return appName;
    }

    public void setAppName(JLabel appName) {
        this.appName = appName;
    }

    public JPanel getLeftPanel() {
        return leftPanel;
    }

    public void setLeftPanel(JPanel leftPanel) {
        this.leftPanel = leftPanel;
    }

    public JButton getLoginBtn() {
        return loginBtn;
    }

    public void setLoginBtn(JButton loginBtn) {
        this.loginBtn = loginBtn;
    }

    public JLabel getLoginLabel() {
        return loginLabel;
    }

    public void setLoginLabel(JLabel loginLabel) {
        this.loginLabel = loginLabel;
    }

    public JPasswordField getPaswordField1() {
        return paswordField1;
    }

    public void setPaswordField1(JPasswordField paswordField1) {
        this.paswordField1 = paswordField1;
    }

    public JPanel getRightPanel() {
        return rightPanel;
    }

    public void setRightPanel(JPanel rightPanel) {
        this.rightPanel = rightPanel;
    }

    public JTextField getUsernameField1() {
        return usernameField1;
    }

    public void setUsernameField1(JTextField usernameField1) {
        this.usernameField1 = usernameField1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Wrapper = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        appDescription = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        usernameField1 = new javax.swing.JTextField();
        paswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1188, 708));

        Wrapper.setBackground(new java.awt.Color(255, 137, 47));
        Wrapper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Wrapper.setPreferredSize(new java.awt.Dimension(1280, 720));
        Wrapper.setLayout(new java.awt.GridLayout(1, 2));

        leftPanel.setBackground(new java.awt.Color(255, 137, 47));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appName.setFont(new java.awt.Font("Prompt Semibold", 0, 64)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("WAIDO-KMITL");
        leftPanel.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        appDescription.setFont(new java.awt.Font("Prompt Medium", 0, 24)); // NOI18N
        appDescription.setForeground(new java.awt.Color(253, 215, 186));
        appDescription.setText("ระบบจัดการบุคลากรและ นักศึกษา");
        leftPanel.add(appDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Wrapper.add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        usernameField1.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        usernameField1.setForeground(new java.awt.Color(153, 153, 153));
        usernameField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField1.setToolTipText("Admin");
        usernameField1.setActionCommand("<Not Set>");
        usernameField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Prompt", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        usernameField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });

        paswordField1.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        paswordField1.setForeground(new java.awt.Color(153, 153, 153));
        paswordField1.setToolTipText("Password");
        paswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Prompt", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        paswordField1.setMargin(new java.awt.Insets(10, 25, 10, 25));
        paswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswordField1ActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 153, 0));
        loginBtn.setFont(new java.awt.Font("Prompt", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("Prompt Semibold", 0, 48)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(184, 96, 29));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(loginLabel)
                .addGap(47, 47, 47)
                .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(loginBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Wrapper.add(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void paswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paswordField1ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Wrapper;
    private javax.swing.JLabel appDescription;
    private javax.swing.JLabel appName;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField paswordField1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField usernameField1;
    // End of variables declaration//GEN-END:variables
}
