package page;

import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author windows
 */
public class NavPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public NavPanel() {
        initComponents();
    }

    public JPanel getBlankPanel() {
        return blankPanel;
    }

    public void setBlankPanel(JPanel blankPanel) {
        this.blankPanel = blankPanel;
    }

    public JButton getFacultyManageBtn() {
        return facultyManageBtn;
    }

    public void setFacultyManageBtn(JButton facultyManageBtn) {
        this.facultyManageBtn = facultyManageBtn;
    }

    public JButton getMainPageBtn() {
        return mainPageBtn;
    }

    public void setMainPageBtn(JButton mainPageBtn) {
        this.mainPageBtn = mainPageBtn;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public JButton getProfessorManageBtn() {
        return professorManageBtn;
    }

    public void setProfessorManageBtn(JButton professorManageBtn) {
        this.professorManageBtn = professorManageBtn;
    }

    public JPanel getSidePanel() {
        return sidePanel;
    }

    public void setSidePanel(JPanel sidePanel) {
        this.sidePanel = sidePanel;
    }

    public JButton getStudentManageBtn() {
        return studentManageBtn;
    }

    public void setStudentManageBtn(JButton studentManageBtn) {
        this.studentManageBtn = studentManageBtn;
    }

    public JButton getSubjectManageBtn() {
        return subjectManageBtn;
    }

    public void setSubjectManageBtn(JButton subjectManageBtn) {
        this.subjectManageBtn = subjectManageBtn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        mainPageBtn = new javax.swing.JButton();
        facultyManageBtn = new javax.swing.JButton();
        subjectManageBtn = new javax.swing.JButton();
        studentManageBtn = new javax.swing.JButton();
        professorManageBtn = new javax.swing.JButton();
        blankPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        mainPanel.setBackground(new java.awt.Color(255, 137, 47));
        mainPanel.setFont(mainPanel.getFont());
        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        sidePanel.setBackground(new java.awt.Color(255, 137, 47));
        sidePanel.setPreferredSize(new java.awt.Dimension(300, 324));

        mainPageBtn.setBackground(new java.awt.Color(228, 109, 18));
        mainPageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        mainPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainPageBtn.setText("หน้าหลัก");
        mainPageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainPageBtn.setIconTextGap(10);
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        facultyManageBtn.setBackground(new java.awt.Color(204, 204, 204));
        facultyManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        facultyManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        facultyManageBtn.setText("จัดการคณะ/สาขา");
        facultyManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        facultyManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facultyManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        facultyManageBtn.setIconTextGap(10);

        subjectManageBtn.setBackground(new java.awt.Color(204, 204, 204));
        subjectManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        subjectManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        subjectManageBtn.setText("จัดการวิชาเรียน");
        subjectManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        subjectManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subjectManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subjectManageBtn.setIconTextGap(10);

        studentManageBtn.setBackground(new java.awt.Color(204, 204, 204));
        studentManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        studentManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        studentManageBtn.setText("จัดการนักศึกษา");
        studentManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        studentManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentManageBtn.setIconTextGap(10);
        studentManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManageBtnActionPerformed(evt);
            }
        });

        professorManageBtn.setBackground(new java.awt.Color(204, 204, 204));
        professorManageBtn.setFont(new java.awt.Font("Prompt", 1, 20)); // NOI18N
        professorManageBtn.setForeground(new java.awt.Color(255, 137, 47));
        professorManageBtn.setText("จัดการอาจารย์");
        professorManageBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        professorManageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        professorManageBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        professorManageBtn.setIconTextGap(10);
        professorManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorManageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(facultyManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
            .addComponent(subjectManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(professorManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(mainPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(facultyManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(subjectManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(studentManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(professorManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        blankPanel.setPreferredSize(new java.awt.Dimension(991, 720));

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(blankPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPageBtnActionPerformed

    private void studentManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentManageBtnActionPerformed

    private void professorManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorManageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton facultyManageBtn;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton professorManageBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton studentManageBtn;
    private javax.swing.JButton subjectManageBtn;
    // End of variables declaration//GEN-END:variables
}
