import java.awt.*;
import javax.swing.*;

public class Login extends JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Wrapper = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        appDescription = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        usernameField1 = new javax.swing.JTextField();
        paswordField1 = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();

        x.setBackground(new java.awt.Color(255, 255, 255));
        x.setPreferredSize(new java.awt.Dimension(733, 936));

        jLabel2.setFont(new java.awt.Font("Prompt", 1, 96)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Login");

        javax.swing.GroupLayout xLayout = new javax.swing.GroupLayout(x);
        x.setLayout(xLayout);
        xLayout.setHorizontalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(172, 172, 172))
        );
        xLayout.setVerticalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waido KMITL");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setName("loginFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 720));

        Wrapper.setBackground(new java.awt.Color(255, 137, 47));
        Wrapper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Wrapper.setPreferredSize(new java.awt.Dimension(1200, 720));
        Wrapper.setLayout(new java.awt.GridLayout(1, 2));

        leftPanel.setBackground(new java.awt.Color(255, 137, 47));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appName.setFont(new java.awt.Font("Prompt Semibold", 0, 64)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("WAIDO-KMITL");
        leftPanel.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        appDescription.setFont(new java.awt.Font("Prompt Medium", 0, 24)); // NOI18N
        appDescription.setForeground(new java.awt.Color(253, 215, 186));
        appDescription.setText("ระบบจัดการบุคลากรและ นักศึกษา");
        leftPanel.add(appDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Wrapper.add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        usernameField1.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        usernameField1.setForeground(new java.awt.Color(153, 153, 153));
        usernameField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameField1.setToolTipText("EARTH");
        usernameField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Prompt", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        usernameField1.setMargin(new java.awt.Insets(10, 25, 10, 25));
        usernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField1ActionPerformed(evt);
            }
        });

        paswordField1.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        paswordField1.setForeground(new java.awt.Color(153, 153, 153));
        paswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Prompt", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        paswordField1.setMargin(new java.awt.Insets(10, 25, 10, 25));
        paswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswordField1ActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 153, 0));
        loginBtn.setFont(new java.awt.Font("Prompt", 1, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("Prompt Semibold", 0, 48)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(184, 96, 29));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(loginLabel)
                .addGap(47, 47, 47)
                .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(loginBtn)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        Wrapper.add(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Wrapper, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField1ActionPerformed

    private void paswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paswordField1ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Wrapper;
    private javax.swing.JLabel appDescription;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField paswordField1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField usernameField1;
    private javax.swing.JPanel x;
    // End of variables declaration//GEN-END:variables
}
