package frame;

import java.awt.*;
import javax.swing.*;
import model.ProfessorModel;

public class AddNewSubjectFrame extends JFrame {

    private ProfessorModel professorModel = new ProfessorModel();

    public AddNewSubjectFrame() {
        initComponents();
        initComboBox();
    }

    public void init() {

    }

    public void initComboBox() {
        subjectProfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(professorModel.getRecordsForComboBox()));
    }

    public JButton getAddSubjectBtn() {
        return this.addSubjectBtn;
    }

    public JTextArea getSubjectDetailTextArea() {
        return subjectDetailTextArea;
    }

    public JTextField getSubjectIDTextField() {
        return subjectIDTextField;
    }

    public JTextField getSubjectNameTextField() {
        return subjectNameTextField;
    }

    public JComboBox<String> getSubjectProfComboBox() {
        return subjectProfComboBox;
    }

    public void config() {
        this.setLayout(new BorderLayout());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        subjectLabel = new javax.swing.JLabel();
        subjectNameTextField = new javax.swing.JTextField();
        subjectID = new javax.swing.JLabel();
        subjectIDTextField = new javax.swing.JTextField();
        subjectProf = new javax.swing.JLabel();
        subjectProfComboBox = new javax.swing.JComboBox<>();
        subjectDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectDetailTextArea = new javax.swing.JTextArea();
        addSubjectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Add a new subject"); // NOI18N
        setResizable(false);

        wrapper.setBackground(new java.awt.Color(255, 255, 255));
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        wrapper.setDoubleBuffered(false);

        subjectLabel.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(255, 137, 47));
        subjectLabel.setText("ชื่อวิชา");

        subjectNameTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        subjectNameTextField.setForeground(new java.awt.Color(154, 154, 154));
        subjectNameTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        subjectID.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        subjectID.setForeground(new java.awt.Color(255, 137, 47));
        subjectID.setText("รหัสวิชา");

        subjectIDTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        subjectIDTextField.setForeground(new java.awt.Color(154, 154, 154));
        subjectIDTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        subjectProf.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        subjectProf.setForeground(new java.awt.Color(255, 137, 47));
        subjectProf.setText("ชื่ออาจารย์ผู้สอนประจำวิชา");

        subjectProfComboBox.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        subjectProfComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ชื่อ นามสกุล", "ชื่อจริง ชื่อไม่จริง", "ชื่อนู้น ชื่อนี้", "FIrstname Lastname" }));
        subjectProfComboBox.setMinimumSize(new java.awt.Dimension(23, 50));
        subjectProfComboBox.setPreferredSize(new java.awt.Dimension(23, 50));

        subjectDetail.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        subjectDetail.setForeground(new java.awt.Color(255, 137, 47));
        subjectDetail.setText("รายละเอียดวิชา");

        subjectDetailTextArea.setColumns(20);
        subjectDetailTextArea.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        subjectDetailTextArea.setLineWrap(true);
        subjectDetailTextArea.setRows(5);
        jScrollPane1.setViewportView(subjectDetailTextArea);

        addSubjectBtn.setBackground(new java.awt.Color(255, 137, 47));
        addSubjectBtn.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        addSubjectBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSubjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addSubjectBtn.setText("เพิ่มวิชา");
        addSubjectBtn.setFocusPainted(false);
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(subjectProfComboBox, 0, 623, Short.MAX_VALUE)
                    .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(subjectID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(subjectProf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(subjectLabel)
                .addGap(18, 18, 18)
                .addComponent(subjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectID)
                .addGap(18, 18, 18)
                .addComponent(subjectIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectProf)
                .addGap(18, 18, 18)
                .addComponent(subjectProfComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectDetail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(wrapper, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subjectDetail;
    private javax.swing.JTextArea subjectDetailTextArea;
    private javax.swing.JLabel subjectID;
    private javax.swing.JTextField subjectIDTextField;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectNameTextField;
    private javax.swing.JLabel subjectProf;
    private javax.swing.JComboBox<String> subjectProfComboBox;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
