package frame;

import java.awt.*;
import javax.swing.*;

public class AddNewStudentFrame extends JFrame {

    public AddNewStudentFrame() {
        initComponents();
    }

    public void init() {

    }

    public void config() {
        this.setLayout(new BorderLayout());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        studentName = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        studentID = new javax.swing.JLabel();
        studentIDTextField = new javax.swing.JTextField();
        studentAge = new javax.swing.JLabel();
        studentAgeTextField = new javax.swing.JTextField();
        studentGender = new javax.swing.JLabel();
        studentGenderTextField = new javax.swing.JTextField();
        studentPhone = new javax.swing.JLabel();
        studentPhoneTextField = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Add a new student"); // NOI18N
        setResizable(false);

        wrapper.setBackground(new java.awt.Color(255, 255, 255));
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        wrapper.setDoubleBuffered(false);

        studentName.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentName.setForeground(new java.awt.Color(255, 137, 47));
        studentName.setText("ชื่อ นามสกุล");

        studentNameTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentNameTextField.setForeground(new java.awt.Color(154, 154, 154));
        studentNameTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        studentID.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentID.setForeground(new java.awt.Color(255, 137, 47));
        studentID.setText("รหัสนักศึกษา");

        studentIDTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentIDTextField.setForeground(new java.awt.Color(154, 154, 154));
        studentIDTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        studentAge.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentAge.setForeground(new java.awt.Color(255, 137, 47));
        studentAge.setText("อายุ");

        studentAgeTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentAgeTextField.setForeground(new java.awt.Color(154, 154, 154));
        studentAgeTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        studentGender.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentGender.setForeground(new java.awt.Color(255, 137, 47));
        studentGender.setText("เพศ");

        studentGenderTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentGenderTextField.setForeground(new java.awt.Color(154, 154, 154));
        studentGenderTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        studentPhone.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentPhone.setForeground(new java.awt.Color(255, 137, 47));
        studentPhone.setText("เบอร์โทรศัพท์");

        studentPhoneTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentPhoneTextField.setForeground(new java.awt.Color(154, 154, 154));
        studentPhoneTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        addStudent.setBackground(new java.awt.Color(255, 137, 47));
        addStudent.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        addStudent.setForeground(new java.awt.Color(255, 255, 255));
        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addStudent.setText("เพิ่มนักเรียน");
        addStudent.setFocusPainted(false);
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(studentIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wrapperLayout.createSequentialGroup()
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(studentAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(studentAgeTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentGenderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(studentGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(studentPhoneTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(studentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(studentName)
                .addGap(18, 18, 18)
                .addComponent(studentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentID)
                .addGap(18, 18, 18)
                .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentAge)
                    .addComponent(studentGender))
                .addGap(18, 18, 18)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentGenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(studentPhone)
                .addGap(18, 18, 18)
                .addComponent(studentPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(wrapper, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JLabel studentAge;
    private javax.swing.JTextField studentAgeTextField;
    private javax.swing.JLabel studentGender;
    private javax.swing.JTextField studentGenderTextField;
    private javax.swing.JLabel studentID;
    private javax.swing.JTextField studentIDTextField;
    private javax.swing.JLabel studentName;
    private javax.swing.JTextField studentNameTextField;
    private javax.swing.JLabel studentPhone;
    private javax.swing.JTextField studentPhoneTextField;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
