package frame;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import model.Student;
import model.StudentModel;

public class AddNewSubjectStudentFrame extends JFrame {

    private StudentModel studentModel = new StudentModel();

    public AddNewSubjectStudentFrame() {
        initComponents();
        setStudentList();
    }

    public void setStudentList() {
        ArrayList<Student> students = studentModel.getStudents();
        for (int i = 0; i < students.size(); i++) {
            this.getStudentNameComboBox().addItem(students.get(i).getFullname() + " ("+students.get(i).getStudentId()+")");
        }

    }

    public JButton getAddStudentBtn() {
        return this.addStudentBtn;
    }

    public JComboBox<String> getStudentNameComboBox() {
        return this.studentNameComboBox;
    }

    public void config() {
        this.setLayout(new BorderLayout());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        studentNameComboBox = new javax.swing.JComboBox<>();
        addStudentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Add a new faculty"); // NOI18N
        setResizable(false);

        wrapper.setBackground(new java.awt.Color(255, 255, 255));
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        wrapper.setDoubleBuffered(false);

        studentLabel.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        studentLabel.setForeground(new java.awt.Color(255, 137, 47));
        studentLabel.setText("เลือกนักศึกษาที่ต้องการเพิ่มเข้าในรายวิชา");

        studentNameComboBox.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        studentNameComboBox.setPreferredSize(new java.awt.Dimension(23, 50));

        addStudentBtn.setBackground(new java.awt.Color(255, 137, 47));
        addStudentBtn.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        addStudentBtn.setForeground(new java.awt.Color(255, 255, 255));
        addStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addStudentBtn.setText("เพิ่มพู้เรียน");
        addStudentBtn.setFocusPainted(false);
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(wrapperLayout.createSequentialGroup()
                        .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addComponent(studentNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(studentLabel)
                .addGap(18, 18, 18)
                .addComponent(studentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(addStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(wrapper, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JComboBox<String> studentNameComboBox;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
