package frame;

import java.awt.*;
import javax.swing.*;

public class AddNewProfessorFrame extends JFrame {

    public AddNewProfessorFrame() {
        initComponents();
    }

    public void init() {

    }

    public void config() {
        this.setLayout(new BorderLayout());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public JButton getAddProfessor() {
        return addProfessor;
    }

    public JTextField getProfessorAgeTextField() {
        return professorAgeTextField;
    }

    public JTextField getProfessorDegreeTextFIeld() {
        return professorDegreeTextField;
    }

    public JTextField getProfessorGenderTextField() {
        return professorGenderTextField;
    }

    public JTextField getProfessorFullnameTextField() {
        return professorFullnameTextField;
    }

    public JTextField getProfessorPhoneTextField() {
        return professorPhoneTextField;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrapper = new javax.swing.JPanel();
        professorFullname = new javax.swing.JLabel();
        professorFullnameTextField = new javax.swing.JTextField();
        professorDegree = new javax.swing.JLabel();
        professorDegreeTextField = new javax.swing.JTextField();
        professorAge = new javax.swing.JLabel();
        professorAgeTextField = new javax.swing.JTextField();
        professorGender = new javax.swing.JLabel();
        professorGenderTextField = new javax.swing.JTextField();
        professorPhone = new javax.swing.JLabel();
        professorPhoneTextField = new javax.swing.JTextField();
        addProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Add a new professor"); // NOI18N
        setResizable(false);

        wrapper.setBackground(new java.awt.Color(255, 255, 255));
        wrapper.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        wrapper.setDoubleBuffered(false);

        professorFullname.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        professorFullname.setForeground(new java.awt.Color(255, 137, 47));
        professorFullname.setText("ชื่อ นามสกุล");

        professorFullnameTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        professorFullnameTextField.setForeground(new java.awt.Color(154, 154, 154));
        professorFullnameTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        professorDegree.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        professorDegree.setForeground(new java.awt.Color(255, 137, 47));
        professorDegree.setText("ระดับการศึกษา");

        professorDegreeTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        professorDegreeTextField.setForeground(new java.awt.Color(154, 154, 154));
        professorDegreeTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        professorAge.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        professorAge.setForeground(new java.awt.Color(255, 137, 47));
        professorAge.setText("อายุ");

        professorAgeTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        professorAgeTextField.setForeground(new java.awt.Color(154, 154, 154));
        professorAgeTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        professorGender.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        professorGender.setForeground(new java.awt.Color(255, 137, 47));
        professorGender.setText("เพศ");

        professorGenderTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        professorGenderTextField.setForeground(new java.awt.Color(154, 154, 154));
        professorGenderTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        professorPhone.setFont(new java.awt.Font("Prompt Medium", 0, 20)); // NOI18N
        professorPhone.setForeground(new java.awt.Color(255, 137, 47));
        professorPhone.setText("เบอร์โทรศัพท์");

        professorPhoneTextField.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        professorPhoneTextField.setForeground(new java.awt.Color(154, 154, 154));
        professorPhoneTextField.setMargin(new java.awt.Insets(10, 10, 10, 10));

        addProfessor.setBackground(new java.awt.Color(255, 137, 47));
        addProfessor.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        addProfessor.setForeground(new java.awt.Color(255, 255, 255));
        addProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addProfessor.setText("เพิ่มอาจารย์");
        addProfessor.setFocusPainted(false);
        addProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrapperLayout = new javax.swing.GroupLayout(wrapper);
        wrapper.setLayout(wrapperLayout);
        wrapperLayout.setHorizontalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professorFullnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(professorDegreeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, wrapperLayout.createSequentialGroup()
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(professorAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(professorAgeTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(professorGenderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(professorGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(professorPhoneTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(professorDegree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professorFullname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professorPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wrapperLayout.setVerticalGroup(
            wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperLayout.createSequentialGroup()
                .addComponent(professorFullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(professorFullnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(professorDegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(professorDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorAge)
                    .addComponent(professorGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(professorGenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professorAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(professorPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(addProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(wrapper, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProfessorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProfessor;
    private javax.swing.JLabel professorAge;
    private javax.swing.JTextField professorAgeTextField;
    private javax.swing.JLabel professorDegree;
    private javax.swing.JTextField professorDegreeTextField;
    private javax.swing.JLabel professorFullname;
    private javax.swing.JTextField professorFullnameTextField;
    private javax.swing.JLabel professorGender;
    private javax.swing.JTextField professorGenderTextField;
    private javax.swing.JLabel professorPhone;
    private javax.swing.JTextField professorPhoneTextField;
    private javax.swing.JPanel wrapper;
    // End of variables declaration//GEN-END:variables
}
