/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package layout;

import components.ContentPanel;
import components.NavPanel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MainLayout extends javax.swing.JPanel {

    /**
     * Creates new form MainLayout
     */
    public MainLayout() {
        initComponents();
    }

    public ContentPanel getContentPanel() {
        return contentPanel;
    }

    public NavPanel getNavPanel() {
        return navPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new components.NavPanel();
        contentPanel = new components.ContentPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());
        add(navPanel, java.awt.BorderLayout.LINE_START);
        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.ContentPanel contentPanel;
    private components.NavPanel navPanel;
    // End of variables declaration//GEN-END:variables
}
